Girl = input("Enter a Girl name ")
Boy1 = input("Enter a Boy name ")
Boy2 = input("Enter a Second Boy name ")
Piece_of_furniture = input("Enter Piece of furniture ")
Food = input("Enter Food ")
Job = input("Enter a Job role ")


print("Once there was a man named "+Boy1+" His girlfriend, "+Girl)
print("Owned a pair of black shoes. She wore them all the time.")
print("In fact, they were "+ Girl +"'s favourite shoes.")
print(Girl +" she liked them so much that she even kept them on when she slept on her. "+Piece_of_furniture)
print("Eventually they began to smell like ."+Food)
print(Boy1+" as beginning not to like being around her so he called up "+Boy2+" to help him make a revenge plot.")
print("They would kidnap the shoes and take them to a dump in the middle of the night.")
print("This was an easy job for "+Boy2+" because he was a "+Job)
print("So that night they snuck out with the shoes.")
print("When they arrived home the sun was just coming up. Pretending like they knew nothing, they ate breakfast which was eggs.")
print("Shortly after, they heard a scream coming up their driveway! "+Girl+" came doing through the door.")
print("My shoes are missing! "+Girl+" cried for so long and to this day she hasn't stopped.")
print(Boy1+" and "+Boy2+" never told her and since they passed away not long ago")
print(Girl+" will never know!")